# DB
source:
    - name: ORD
      type: mysql
      jdbcUrl: jdbc:mysql://mysql.sqlpub.com:3306/dingchao_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      driverClass: com.mysql.cj.jdbc.Driver
      username: dingchao
      password: 6049773e1914457d


dest:
    - name: ORD
      type: mysql
      jdbcUrl: jdbc:mysql://mysql.sqlpub.com:3306/dingchao_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      driverClass: com.mysql.cj.jdbc.Driver
      username: dingchao
      password: 6049773e1914457d


jobs:
    - name: daily_today_on_history
      type: daily

      sourceName: ORD
      sourceTableName: api_today_on_history
      sourceSqlQuery: select * from api_today_on_history
      ingestEnabled: Y

      destName: ORD
      destTableName: bronze_daily


    - name: hourly_today_on_history
      type: hourly

      sourceName: ORD
      sourceTableName: api_today_on_history
      sourceSqlQuery: select * from api_today_on_history
      ingestEnabled: Y

      destName: ORD
      destTableName: bronze_daily


